language: r
cache: packages
script:
  - sudo apt-get install texlive-latex-extra texlive-latex-recommended biber latexmk
  - make
sudo: required

r_binary_packages:
  - ggplot2
  - data.table
  - haven
  - openxlsx
  - readxl
  - dplyr
  - tikzDevice
  - sandwich
  - lmtest
  - data.table
  - reshape2
  - tidyr
  - knitr

r_packages:
  - devtools
  - rio
  - broom
