language: r
cache: packages
script:  
  - make
sudo: required

r_binary_packages:
  - ggplot2
  - data.table
  - haven
  - openxlsx
  - readxl
  - dplyr
  - tikzDevice
  - sandwich
  - lmtest
  - data.table
  - reshape2
  - tidyr

r_packages:
  - devtools
  - rio
  - broom
